# Generated by Django 5.2.6 on 2025-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_covers/'),
        ),
        migrations.AddField(
            model_name='educationalsection',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='section_headers/'),
        ),
    ]
