# Generated by Django 5.2.6 on 2025-11-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_cover_image_educationalsection_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalsection',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='section_content/'),
        ),
    ]
