# Generated by Django 5.2.7 on 2025-11-11 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sectionimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('security', 'Security'), ('progress', 'Progress'), ('quiz', 'Quiz'), ('game', 'Game'), ('profile', 'Profile'), ('content', 'Content'), ('download', 'Download'), ('system', 'System')], max_length=20)),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Changed'), ('failed_login', 'Failed Login Attempt'), ('profile_update', 'Profile Updated'), ('avatar_upload', 'Avatar Uploaded'), ('lesson_started', 'Lesson Started'), ('lesson_completed', 'Lesson Completed'), ('lesson_viewed', 'Lesson Viewed'), ('quiz_started', 'Quiz Started'), ('quiz_completed', 'Quiz Completed'), ('quiz_passed', 'Quiz Passed'), ('quiz_failed', 'Quiz Failed'), ('game_started', 'Game Started'), ('game_completed', 'Game Completed'), ('game_score', 'Game Score Recorded'), ('content_viewed', 'Content Viewed'), ('video_watched', 'Video Watched'), ('festival_tour', 'Festival Tour Visited'), ('file_downloaded', 'File Downloaded'), ('pdf_downloaded', 'PDF Downloaded'), ('account_created', 'Account Created'), ('account_blocked', 'Account Blocked'), ('account_unblocked', 'Account Unblocked')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('quiz_id', models.IntegerField(blank=True, null=True)),
                ('game_id', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.article')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.mediaasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category', '-created_at'], name='core_activi_user_id_5b7c0a_idx'), models.Index(fields=['category', '-created_at'], name='core_activi_categor_969ef1_idx'), models.Index(fields=['-created_at'], name='core_activi_created_3d0bd9_idx')],
            },
        ),
    ]
