# Generated by Django 5.2.6 on 2025-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('festival_date', models.DateTimeField(blank=True, help_text='The date and time when the festival starts', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Festival Date',
                'verbose_name_plural': 'Festival Date',
            },
        ),
    ]
