# Generated by Django 5.2.7 on 2025-11-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_festivaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalsection',
            name='category',
            field=models.CharField(choices=[('planting', 'Planting'), ('cultural', 'Cultural'), ('historical', 'Historical'), ('economic', 'Economic Value')], default='planting', max_length=50),
        ),
    ]
