# Generated by Django 5.2.7 on 2025-11-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_educationalsection_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(help_text='YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500)),
                ('caption', models.CharField(blank=True, help_text='Optional description or caption for the video', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_videos', to='core.educationalsection')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
