# Generated by Django 5.2.7 on 2025-11-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sectionvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
