# Generated by Django 5.2.7 on 2025-11-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, default='', help_text='Enter the exact correct answer as it appears in choices', max_length=200),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the quiz', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, default='', help_text='Enter choices separated by commas (e.g., Choice A, Choice B, Choice C)'),
        ),
    ]
