# Generated by Django 5.2.7 on 2025-11-03 02:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_studentprofile_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game_type', models.CharField(choices=[('word_scramble', 'Word Scramble'), ('drag_drop', 'Drag and Drop Sorting'), ('image_identification', 'Image Identification'), ('memory_match', 'Memory Matching'), ('multiple_choice_image', 'Multiple Choice with Images')], max_length=30)),
                ('description', models.TextField(help_text='Learning goal and game instructions')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time limit in seconds (optional)', null=True)),
                ('points_per_correct', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='core.article')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=0)),
                ('time_taken', models.IntegerField(blank=True, help_text='Time in seconds', null=True)),
                ('answers', models.TextField(help_text='JSON of user answers')),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('question_text', models.TextField(help_text='Question prompt or instruction')),
                ('word', models.CharField(blank=True, help_text='Word Scramble: the word to unscramble', max_length=100)),
                ('correct_sequence', models.TextField(blank=True, help_text="Drag-Drop: JSON array of correct order, e.g. ['Step 1', 'Step 2']")),
                ('correct_answer', models.CharField(blank=True, help_text='Image ID / MCQ: correct answer text', max_length=200)),
                ('memory_pairs', models.TextField(blank=True, help_text="Memory Match: JSON object of pairs, e.g. {'Arrowroot': 'Plant used for Minasa flour'}")),
                ('explanation', models.TextField(blank=True, help_text='Educational explanation shown after answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(help_text='Option label/text', max_length=200)),
                ('option_image', models.ImageField(blank=True, help_text='Image for this option', null=True, upload_to='game_images/')),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='games.gamequestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
