# Generated by Django 5.2.7 on 2025-11-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='correct_answers',
            field=models.TextField(blank=True, help_text="Drag-Drop: Correct answers for each blank (comma-separated), e.g. 'piper, peck of'"),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='extra_choices',
            field=models.TextField(blank=True, help_text="Drag-Drop: Additional wrong choices (comma-separated), e.g. 'pepper, pack, pick'"),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='sentence_template',
            field=models.TextField(blank=True, help_text="Drag-Drop: Sentence with blanks marked by * or _, e.g. 'Peter * picked a * peckpeck'"),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='correct_sequence',
            field=models.TextField(blank=True, help_text="Drag-Drop Sorting: JSON array of correct order, e.g. ['Step 1', 'Step 2']"),
        ),
    ]
