# Generated by Django 5.2.7 on 2025-11-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gamequestion_correct_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Image Identification: The image to identify', null=True, upload_to='game_images/'),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='text_choices',
            field=models.TextField(blank=True, help_text="Image Identification: Text choices (comma-separated), e.g. 'Arrowroot leaf, Cassava root, Minasa flour, Rice grain'"),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='correct_answer',
            field=models.CharField(blank=True, help_text='Image Identification: The correct text answer (must match one of the choices)', max_length=200),
        ),
    ]
