# Generated by Django 5.2.7 on 2025-11-05 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamequestion_question_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Image Identification: The image to identify (jpg, jpeg, png, gif, webp only)', null=True, upload_to='game_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
