# Generated by Django 5.2.7 on 2025-11-06 02:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_gamequestion_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='grid_size',
            field=models.CharField(blank=True, choices=[('2x2', '2x2 (2 pairs)'), ('3x3', '3x3 (4 pairs - 1 extra)'), ('4x4', '4x4 (8 pairs)'), ('5x5', '5x5 (12 pairs - 1 extra)'), ('6x6', '6x6 (18 pairs)')], help_text='Memory Match: Grid size for image-based memory game', max_length=10),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_10',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_11',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_12',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_13',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_14',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_15',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_16',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_17',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_18',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_5',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_6',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_7',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_8',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
        migrations.AddField(
            model_name='gamequestion',
            name='memory_image_9',
            field=models.ImageField(blank=True, null=True, upload_to='game_images/memory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])]),
        ),
    ]
