# Generated by Django 5.2.7 on 2025-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_gamequestion_grid_size_gamequestion_memory_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='grid_size',
            field=models.CharField(blank=True, choices=[('2x2', '2x2 (2 pairs)'), ('3x3', '3x3 (3 pairs)'), ('4x4', '4x4 (4 pairs)'), ('5x5', '5x5 (5 pairs)'), ('6x6', '6x6 (6 pairs)'), ('7x7', '7x7 (7 pairs)'), ('8x8', '8x8 (8 pairs)'), ('9x9', '9x9 (9 pairs)')], help_text='Memory Match: Grid size for image-based memory game', max_length=10),
        ),
    ]
