# Generated by Django 5.2.7 on 2025-11-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_gamequestion_grid_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in game list'),
        ),
    ]
