# Generated by Django 5.2.7 on 2025-11-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_game_options_game_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('word_scramble', 'Word Scramble'), ('drag_drop', 'Drag and Drop Sorting'), ('image_identification', 'Image Identification'), ('memory_match', 'Memory Matching')], max_length=30),
        ),
    ]
